# Generated by Django 4.2.6 on 2023-10-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('movimiento_debe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movimiento_haber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_deudor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_acreedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesoftapp.cuenta')),
            ],
        ),
    ]
