# Generated by Django 4.2.6 on 2023-10-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codesoftapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='saldo_acreedor',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='saldo_deudor',
        ),
    ]
