# Generated by Django 4.2.6 on 2023-10-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesoftapp', '0002_remove_transaccion_saldo_acreedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('haber_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
