# Generated by Django 4.2.6 on 2023-10-23 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codesoftapp', '0003_resumencuentas'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumencuentas',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resumen_cuentas', to='codesoftapp.cuenta'),
            preserve_default=False,
        ),
    ]
