# Generated by Django 4.2.6 on 2023-10-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesoftapp', '0004_resumencuentas_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumencuentas',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
