# Generated by Django 4.2.6 on 2023-10-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codesoftapp', '0005_resumencuentas_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='resumencuentas',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='codesoftapp.periodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='codesoftapp.periodo'),
            preserve_default=False,
        ),
    ]
