# Generated by Django 4.2.6 on 2023-10-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesoftapp', '0006_periodo_resumencuentas_periodo_transaccion_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('puesto_trabajo', models.CharField(max_length=100)),
                ('pago_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('septimo_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacaciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_cancelado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aguinaldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insaforp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_real', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
