# Generated by Django 4.2.6 on 2023-10-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesoftapp', '0007_manodeobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='manodeobra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
