# Generated by Django 4.2.7 on 2023-11-07 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codesoftapp', '0009_remove_manodeobra_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_utilidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codesoftapp.periodo')),
            ],
        ),
    ]
